default:
  image:
    name: $GOLANG_IMAGE
  tags:
    - ord1-tenant

stages:
  - test
  - build

variables:
  GOLANG_VERSION: "1.20.7"
  GOLANG_IMAGE_SUB_TAG: bullseye
  GOLANG_IMAGE: golang:$GOLANG_VERSION-$GOLANG_IMAGE_SUB_TAG
  NODE_VERSION: "18.17.1"
  DEPLOY_IMAGE: debian:11.4-slim
  KO_VERSION: "0.14.1"

  KO_DOCKER_REPO: $CI_REGISTRY_IMAGE

  FIXED_IMAGE_TAG: $CI_COMMIT_SHORT_SHA

golang-test:
  stage: test
  script:
    - go mod download
    - go fmt ./...
    - go vet -v ./...
    - go test -v ./...

build:
  stage: build
  before_script:
    - | # Generate registry credentials
      echo "Build triggered by $CI_PIPELINE_SOURCE"
      echo "Generating registry auth in ${HOME}/.docker/config.json"
      mkdir -p ${HOME}/.docker
      echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > ${HOME}/.docker/config.json
    - | # Install ko
      OS=Linux
      ARCH=x86_64
      echo "Installing ko @ v${KO_VERSION} for ${ARCH}"
      curl -sL https://github.com/google/ko/releases/download/v${KO_VERSION}/ko_${KO_VERSION}_${OS}_${ARCH}.tar.gz | tar xvzf - -C /usr/local/bin ko
      chmod +x /usr/local/bin/ko
  script:
    - export SOURCE_DATE_EPOCH=$(date +%s)
    - export KO_DATA_DATE_EPOCH=$(git log -1 --format='%ct')
    - ko build ./cmd/kourier --bare -t "$FIXED_IMAGE_TAG"
